### ISSUE TITLE
Move license settings to its own setting category

### ISSUE THREAD

**Issue by tarmot** [tarmot/wp-cc-plugin#23]
It's a bit hard to find the license settings from the general settings in wp-admin. I'd like to see them in a separate settings category of their own.

**Comment by BjornW** [comment]
There's a plugin proliferation of menu's within the WordPress community which causes the Dashboard menu items on the left to become very long. I'd prefer to keep things simple. Therefor I suggest we add our license settings to the general settings page for now until we get feedback from users proving otherwise.
